ENABLE_LINTERS:
  - ANSIBLE_ANSIBLE_LINT
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
APPLY_FIXES:
  - ANSIBLE_ANSIBLE_LINT
  - MARKDOWN_MARKDOWNLINT
  - YAML_YAMLLINT
ANSIBLE_DIRECTORY: .
MARKDOWN_MARKDOWNLINT_DISABLE_ERRORS: false
SHOW_ELAPSED_TIME: true
